version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/loan_db?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HIKARI_MAXIMUM_POOL_SIZE=10
      - HIKARI_MINIMUM_IDLE=5
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=loan_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge 